allow the foreign common point to be manually specified

diff --git a/evergreen b/evergreen
--- a/evergreen
+++ b/evergreen
@@ -28,10 +28,27 @@ case "$shwrapnel_cmdname" in
             shwrapnel set_args "${args[@]}"
 
             if [ "$EVERGREEN_COMMON_POINT" ]; then
+				case "$EVERGREEN_COMMON_POINT" in
+					*=*)
+						EVERGREEN_COMMON_POINT_FOREIGN="${EVERGREEN_COMMON_POINT#*=}"
+						EVERGREEN_COMMON_POINT="${EVERGREEN_COMMON_POINT%=*}"
+						;;
+					*:*)
+						EVERGREEN_COMMON_POINT_FOREIGN="${EVERGREEN_COMMON_POINT#*:}"
+						EVERGREEN_COMMON_POINT="${EVERGREEN_COMMON_POINT%:*}"
+						;;
+					*)
+						EVERGREEN_COMMON_POINT_FOREIGN="$(git show --no-patch --format='format:%B' "$EVERGREEN_COMMON_POINT" | grep -E -o -m 1 '\<[0-9a-fA-F]{40}\>')"
+						if [ "$EVERGREEN_COMMON_POINT_FOREIGN" = "" ]; then
+							echo "$0: Unable to identify foreign common point from the commit message of $EVERGREEN_COMMON_POINT" 1>&2
+							exit 1
+						fi
+						;;
+				esac
                 export EVERGREEN_COMMON_POINT
-                export EVERGREEN_COMMON_POINT_FOREIGN="$(git show --no-patch --format='format:%B' "$EVERGREEN_COMMON_POINT" | grep -E -o -m 1 '\<[0-9a-fA-F]{40}\>')"
+                export EVERGREEN_COMMON_POINT_FOREIGN
                 if [ "$EVERGREEN_COMMON_POINT_FOREIGN" = "" ]; then
-                    echo "$0: Unable to identify foreign common point from the commit message of $EVERGREEN_COMMON_POINT" 1>&2
+                    echo "$0: Empty foreign common point" 1>&2
                     exit 1
                 fi
 
